### ISSUE TITLE
Feature: FOLDERS section

### ISSUE THREAD

**Issue by Rashmi-Wijesekara** [Rashmi-Wijesekara/Tabsaver-chrome-extension#18]
# Epic Title

Feature: FOLDERS section

## Epic Description

- A new section would be created which gives the ability to save similar kinds of tabs as a group together.
- A dropdown menu should be created at the home section, under the input field. When a new tab is saved, we can select a particular folder to group similar kinds of tabs.
- Also if there are any tabs that do not have already been saved into a folder, should be able to store in a folder later.

## List of Tasks

- [ ] [Task: Dropdown menu to add the tab into a folder](https://github.com/Rashmi-Wijesekara/Tabsaver-chrome-extension/issues/14)
- [ ] [Task: Create new folders in the FOLDERS section](https://github.com/Rashmi-Wijesekara/Tabsaver-chrome-extension/issues/19)
- [ ] [Task: Display the saved tabs inside the folders](https://github.com/Rashmi-Wijesekara/Tabsaver-chrome-extension/issues/20)
