### ISSUE TITLE
Feature: improve ALL TABS section

### ISSUE THREAD

**Issue by Rashmi-Wijesekara** [Rashmi-Wijesekara/Tabsaver-chrome-extension#4]
# Epic Title

Feature: improve ALL TABS section

## Epic Description

This feature will add,
- move the DELETE ALL button to the all tabs section
- 2 arrow buttons in the all tabs section to change the tabs order
- delete button to each and every tab

## List of Tasks

- [ ] [Task 1: move the DELETE ALL button to ALL TABS section](https://github.com/Rashmi-Wijesekara/Tabsaver-chrome-extension/issues/5)
- [ ] [Task 2: changing the order of the ALL TABS](https://github.com/Rashmi-Wijesekara/Tabsaver-chrome-extension/issues/6)
- [ ] [Task 3: deleting tabs one by one](https://github.com/Rashmi-Wijesekara/Tabsaver-chrome-extension/issues/7)
